# Generated by Django 3.2.9 on 2021-11-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category1',
            field=models.ManyToManyField(related_name='category1', to='shop.ProductCategory'),
        ),
    ]
